### ISSUE TITLE
Standalone functionaility

### ISSUE THREAD

**Issue by jobyburk** [aMediocreDad/jal#1]
Hey! First off, let me say thank you! When I first bought Foundry, after having used Roll20 for years, I was hoping fragment link functionality was available out of the box. While disappointed, I carried on. However, I'm very stoked to have my hopes renewed!

That being said, I stumbled upon this on Foundry's mod menu. I glossed over the part about this being a library to use in other modules. I installed it and tried to get it to work but no dice. I'm assuming there's no way it will work standalone. If not, do you think it ever will, or will someone have to integrate it into their own library? Either way, excited to see what plays out. Let me know!

**Comment by aMediocreDad** [comment]
Hey! Did you ask me about this in Discord too?

If not, this module/library does work standalone. Make sure your link is identical to the heading (case sensitive*). 

*Note to self: I may actually change this to be case-insensitive.

**Comment by jobyburk** [comment]
I did not, at least to my recollection.

I will have to try it again when I get home. I did it in a fresh world for
testing purposes and couldn't get it to function. Will let you know!

**Comment by jobyburk** [comment]
Alright, I was able to get this to work! I misunderstood the formatting required. The way I read your short explanation, I thought it worked like actual fragment links, in that the tag required an ID property, which was the part being referenced. I was not aware the actual text between the tag was what was being referenced. I might suggest to make that a little more clear in your Wiki section. You might also add that curly brackets after the initial link do function to replace the text of what the link says (instead of being "Journal Entry: Heading". Glad that still functions!

So, yeah, this is really awesome! Is there any plan to extend this so that it doesn't require headers to function? Would it theoretically be possible to point to different types of tags? I realize this would require a complete re-write, but I didn't know if that was possible at all in your estimation.

**Comment by aMediocreDad** [comment]
Hey! Great. Yeah this was actually inspired more by Markdown than HTML fragments. I should go and fix that. The rationale behind this is that this is instantly compatible with the journal entries people have already made and requires only changing the links pointing to those journal entries. As the author of the Forbidden Lands modules this leaves me with significantly less work. 

That said I can certainly implement an id-tag lookup as a priority.

And I'll go ahead and fix the readme to specify that custom naming still works as expected.

**Comment by aMediocreDad** [comment]
This now has a solution in the V9 compatible version. 

See https://github.com/aMediocreDad/jal/releases/tag/v2.0.0

**Comment by jobyburk** [comment]
That is awesome, man! I'll play with it when I get home!

**Comment by jobyburk** [comment]
Finally got around to playing around with this. Works great in my test
world, man. Great work!

The only problem is that I've been using Monk's Enhanced Journal for a
while, and it does not function there at all. I might see if I can come up
with a patch.
