### ISSUE TITLE
module.json for 4.2.0 still contains version 4.1.0

### ISSUE THREAD

**Issue by farling42** [aMediocreDad/jal#11]
The module.json on release 4.2.0 needs updating to have the version field set to 4.2.0

**Comment by r-valyar** [comment]
I presume this is why the update to same version and URL redirect occurs on every update run?

![image](https://github.com/aMediocreDad/jal/assets/63558984/454697be-1aaf-41d1-a66b-9e82a4cc83e4)

**Comment by aMediocreDad** [comment]
Yes, sorry. The module.json has been updated and I have replaced the artifacts in the release. Pressing the update button now should properly install the latest version.
