### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by Tatonker** [aMediocreDad/jal#7]
Hi,

I'm sure this is perfectly simple, but I'm struggling to get this set up in my game world. I have registered the module as a dependency in my 'shared compendium' module, is that sufficient? I have both the shared compendium module and JAL activated in my world but only the link to the beginning of a journal is created rather than the link to the header.

Do you have any suggestions? Troubleshooting tips I could try?

Thanks,

Tatonker

**Comment by aMediocreDad** [comment]
Hi,

I am not sure what the shared compendium module is. Also I would need to know if you are using V9 or V10.

**Comment by Tatonker** [comment]
Sorry, I was just coming back in to update the Foundry version (v10.285). I'm also on D&D 5e 2.0.2.

The shared compendium module is a personal module that lets you create packs for items, journals, actors etc... that you control and exist in all worlds that you have the module enabled. It allows for very easy sharing of data between your worlds (such as content imported from DDBeyond using Mr Primate's DDB Importer module).

It is basically this:

https://fgen-mxzf-prod.herokuapp.com/module/create

On my Foundry home page under modules, I see JAL registered as a dependency of the share compendium module.

Thanks,

Tatonker

**Comment by aMediocreDad** [comment]
And you are dragging a heading from a compendium journalpage onto a scene?

In v10 this module only adds support for subheadings in journalpages as scene notes. Nothing else.

**Comment by Tatonker** [comment]
I am opening a journal from the journal sidebar, then dragging a heading on a journal page to the scene.

When dragging "Buried Treasures" (which is set up as an H3) from the journal to the scene, the 'Notes' window appears and only gives the option of choosing one of the parent pages eg. "Locations in Bremen".

![image](https://user-images.githubusercontent.com/70360365/191173813-1c96a579-2c51-4756-a293-d382e19eeebe.png)

**Comment by Tatonker** [comment]
Here's the screenshot of the dependency of the module:

![image](https://user-images.githubusercontent.com/70360365/191174371-5f843b52-6ddb-470d-a2e9-51eaa3e56a53.png)

I'm probably doing something really simple wrong, or, using the 'shared compendium module' is not a viable use case.

**Comment by aMediocreDad** [comment]
It could certainly be that journals from compendiums aren't working.

That said, there is no UI indicating that you have a heading, unfortunately. If it's not too much hacky code needed to get an indicator in ui up I might do that. 

What you should do is drag that heading onto the scene and then click "update note" in the dialog that pops up. 

That last step there is required for a note to be created at all. You can of course give it a custom label and so on.

**Comment by Tatonker** [comment]
The journal entries aren't from a shared compendium, they are entries in my world itself (not from a shared compendium).

When I drag the heading to the scene and hit 'update note' it creates the journal note at the top level of the journal, not the heading.

If it is due to having it as a dependency in my shared compendium (I thought the dependency was just to make sure that JAL was activated but maybe I'm misunderstanding), then is there somewhere else I should be putting it? I don't really want to play around in the 5e system json and there's no other module that I 'control' that I'd feel comfortable adding the JAL dependency to.

**Comment by aMediocreDad** [comment]
Then it should be working. I'll try to replicate the setup with your system and see if I can replicate the issue.

**Comment by aMediocreDad** [comment]
@Tatonker Tested in latest 5e (2.0.2) and V10 (10.285). Here's a gif of how it should work:
![example_workflow_low](https://user-images.githubusercontent.com/9851733/191176690-e5a17f78-9bb2-4096-9611-e6a8ec3ab054.gif)

You'll notice as the journal entry opens it's scrolled down to the bottom..

**Comment by Tatonker** [comment]
Hmmm, ok I think it is actually working. I was just being thrown as the map note name wasn't sycing up with the heading, and I was using a small journal which was 'skewing' the results. Using a much bigger journal leads to a more obvious result.

So just to be clear, I'll need to update the map note 'text label' to be the heading that I want it to link back to as it isn't updated automatically. I think that was what was throwing me in particular.

Thanks, I think that helps me out.

Tatonker

**Comment by Tatonker** [comment]
Here's what it looks like using the 'Clever Beast' heading:

[JAL.webm](https://user-images.githubusercontent.com/70360365/191178889-b937653b-e1d0-458e-b925-5d7dedc5c9be.webm)

**Comment by aMediocreDad** [comment]
> So just to be clear, I'll need to update the map note 'text label' to be the heading that I want it to link back to as it isn't updated automatically. I think that was what was throwing me in particular.

Yes, that is correct. The module doesn't do any work before you "Update Note". That said, good call. I could probably inject the heading as label in that dialog that pops up too. I'll look into it.

**Comment by Tatonker** [comment]
That would be brilliant, thank you so much for your support / help.
